force-app/main/default/objects/Account/fields/AccountContactRelationSum__c.field-meta.xml
<CustomField>
    <fullName>AccountContactRelationSum__c</fullName>
    <label>AccountContactRelationSum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Users__c.field-meta.xml
<CustomField>
    <fullName>Business_Users__c</fullName>
    <description>Contains the number of related contacts with the role &quot;Business User&quot;</description>
    <label>Business Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContactsSum__c.field-meta.xml
<CustomField>
    <fullName>ContactsSum__c</fullName>
    <description>Sum of all the contacts that an Account has. Is updated by Trigger.</description>
    <label>ContactsSum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Decision_Makers__c.field-meta.xml
<CustomField>
    <fullName>Decision_Makers__c</fullName>
    <description>Contains the number of related contacts with the role &quot;Decision Maker&quot;</description>
    <label>Decision Makers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/OpportunitiesSum__c.field-meta.xml
<CustomField>
    <fullName>OpportunitiesSum__c</fullName>
    <description>Sum of all the opportunities that an Account has. Is updated by Trigger.</description>
    <label>OpportunitiesSum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountController.cls
/**********************************************************************************
* Name             AccountController.cls
* Author          Andres Pereyra
* Date            26/08/24
* Description     This is an Apex Class which is used mainly by two LWC components via wire service 
***********************************************************************************
* MODIFICATION LOG
* Version            Developer          Date               Description
* ------------------------------------------------------------------------------
* 1.0                Andres Pereyra     03 January 2025           Initial Creation 
* *********************************************************************************/

public without sharing class AccountController {
    @AuraEnabled(cacheable=true)
    public static List<Account> getAccounts() {
        return [
            SELECT Id, Name, TickerSymbol, AnnualRevenue, Business_Users__c, Decision_Makers__c, OpportunitiesSum__c, ContactsSum__c, AccountContactRelationSum__c,
            (SELECT Id, CreatedDate, Contact.Name FROM AccountContactRelations ORDER BY Contact.Name ASC)
            FROM Account
            ORDER BY Name ASC
        ];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Contact> getSingleAccountRelatedContacts(Id accountId) {
        return [
            SELECT Id, Name, CreatedDate, AccountId
            FROM Contact
            WHERE AccountId = :accountId
            ORDER BY Name ASC
        ];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Opportunity> getSingleAccountRelatedOportunitties(Id accountId) {
        return [
            SELECT Id, Name, Amount, AccountId
            FROM Opportunity
            WHERE AccountId = :accountId
            ORDER BY Name ASC
        ];
    }
}