force-app/main/default/objects/Account/fields/AccountContactRelationSum__c.field-meta.xml
<CustomField>
    <fullName>AccountContactRelationSum__c</fullName>
    <label>AccountContactRelationSum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Users__c.field-meta.xml
<CustomField>
    <fullName>Business_Users__c</fullName>
    <description>Contains the number of related contacts with the role &quot;Business User&quot;</description>
    <label>Business Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContactsSum__c.field-meta.xml
<CustomField>
    <fullName>ContactsSum__c</fullName>
    <description>Sum of all the contacts that an Account has. Is updated by Trigger.</description>
    <label>ContactsSum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Decision_Makers__c.field-meta.xml
<CustomField>
    <fullName>Decision_Makers__c</fullName>
    <description>Contains the number of related contacts with the role &quot;Decision Maker&quot;</description>
    <label>Decision Makers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/OpportunitiesSum__c.field-meta.xml
<CustomField>
    <fullName>OpportunitiesSum__c</fullName>
    <description>Sum of all the opportunities that an Account has. Is updated by Trigger.</description>
    <label>OpportunitiesSum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountControllerTest.cls
/* @Description  This is a Test Class for the Apex Class AccountController.cls
*******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer          Date               Description
*-------------------------------------------------------------------------------------------
*  1.0            Andres Pereyra      06/01/2025         Initial Creation                                                
*******************************************************************************************/

@IsTest
public class AccountControllerTest {

        @testSetup 
    static void setup() {   
        /* 
'Besluitvormer' --> 'Decision Maker'
'Zakelijke gebruiker' --> 'Business User'
*/          
        // Create test data
        List<Account> accounts = TestDataFactory.createAccounts(4);   
    }

     @IsTest
    static void testGetAccounts() {
        List<Account> accounts = [SELECT Id, Name, TickerSymbol, AnnualRevenue, Business_Users__c, Decision_Makers__c, OpportunitiesSum__c, ContactsSum__c, AccountContactRelationSum__c FROM Account LIMIT 199];
        Set<Id> accountIdSet = new Set<Id>();
        for(Account acc : accounts){
            accountIdSet.add(acc.Id);
        }
        
        List<Account> results = new List<Account>();
        
        Test.startTest();
        results = AccountController.getAccounts();
        Test.stopTest();
        
        System.assertEquals(results.size(), accounts.size(), 'Should match');
        
    }
    
    @IsTest
    static void testGetSingleAccountRelatedContacts() {
        List<Account> account = [SELECT Id, Name, TickerSymbol, AnnualRevenue, Business_Users__c, Decision_Makers__c, OpportunitiesSum__c, ContactsSum__c, AccountContactRelationSum__c FROM Account LIMIT 1];

        List<Contact> contacts = TestDataFactory.createContacts(4, account);
        List<Contact> results = new List<Contact>();
        
        Test.startTest();
        results = AccountController.getSingleAccountRelatedContacts(account[0].Id);
        Test.stopTest();
        
        System.assertEquals(contacts.size(), results.size(), 'Contacts count should be 4');
    }
    
        @IsTest
    static void testGetSingleAccountRelatedOportunitties() {
        List<Account> account = [SELECT Id, Name, TickerSymbol, AnnualRevenue, Business_Users__c, Decision_Makers__c, OpportunitiesSum__c, ContactsSum__c, AccountContactRelationSum__c FROM Account LIMIT 1];

        List<Opportunity> opportunities = TestDataFactory.createOpportunities(4, account);
        List<Opportunity> results = new List<Opportunity>();
        
        Test.startTest();
        results = AccountController.getSingleAccountRelatedOportunitties(account[0].Id);
        Test.stopTest();
        
        System.assertEquals(opportunities.size(), results.size(), 'Opportunities count should be 4');
    }
}